export const CONTEXT = 'containers/ForgotPassword';
export const [
  HANDLE_SUBMIT_CHANGE_PASSWORD,
  HANDLE_SUBMIT_CHANGE_PASSWORD_SUCCESS,
  HANDLE_SUBMIT_CHANGE_PASSWORD_FAILURE,
] = [
  `${CONTEXT}HANDLE_SUBMIT_CHANGE_PASSWORD`,
  `${CONTEXT}HANDLE_SUBMIT_CHANGE_PASSWORD_SUCCESS`,
  `${CONTEXT}HANDLE_SUBMIT_CHANGE_PASSWORD_FAILURE`,
];
