export const CONTEXT = 'container/register-page';
export const HANDLE_CHANGE_USER = `${CONTEXT}HANDLE_CHANGE_USER`;
export const [
  HANDLE_SUBMIT_REGISTER_USER,
  HANDLE_SUBMIT_REGISTER_USER_SUCCESS,
  HANDLE_SUBMIT_REGISTER_USER_FAILURE,
] = [
  `${CONTEXT}HANDLE_SUBMIT_REGISTER_USER`,
  `${CONTEXT}HANDLE_SUBMIT_REGISTER_USER_SUCCESS`,
  `${CONTEXT}HANDLE_SUBMIT_REGISTER_USER_FAILURE`,
];
