export const CONTEXT = 'containers/LoginPage';
export const [
  HANDLE_SUBMIT_LOGIN,
  HANDLE_SUBMIT_LOGIN_SUCCESS,
  HANDLE_SUBMIT_LOGIN_FAILURE,
] = [
  `${CONTEXT}HANDLE_SUBMIT_LOGIN`,
  `${CONTEXT}HANDLE_SUBMIT_LOGIN_SUCCESS`,
  `${CONTEXT}HANDLE_SUBMIT_LOGIN_FAILURE`,
];

export const HANDLE_INPUT_CHANGE = `${CONTEXT}HANDLE_INPUT_CHANGE`;
export const HANDLE_RESET_LOGIN_FORM = `${CONTEXT}HANDLE_RESET_LOGIN_FORM`;
export const HANDLE_SET_DEFAULT_VALUE = `${CONTEXT}HANDLE_SET_DEFAULT_VALUE`;
export const HANDLE_CHANGE_REMEMBER = `${CONTEXT}HANDLE_CHANGE_REMEMBER`;
