export const CONTEXT = 'container/App';
export const ADD_NOTIFICATION = `${CONTEXT}ADD_NOTIFICATION`;
export const RESET_NOTIFICATION_LIST = `${CONTEXT}RESET_NOTIFICATION_LIST`;
export const DELETE_NOTIFICATION = `${CONTEXT}DELETE_NOTIFICATION`;
